export const PERSON_LIST = "PERSON_LIST";
export const PERSON_LIST_REQUEST = "PERSON_LIST_REQUEST";
export const PERSON_LIST_SUCCESS = "PERSON_LIST_SUCCESS";
export const PERSON_LIST_ERROR = "PERSON_LIST_ERROR";

export const PERSON_CREATE = "PERSON_CREATE";
export const PERSON_CREATE_REQUEST = "PERSON_CREATE_REQUEST";
export const PERSON_CREATE_SUCCESS = "PERSON_CREATE_SUCCESS";
export const PERSON_CREATE_ERROR = "PERSON_CREATE_ERROR";
export const PERSON_CREATE_RESET = "PERSON_CREATE_RESET";

export const PERSON_UPDATE = "PERSON_UPDATE";
export const PERSON_UPDATE_REQUEST = "PERSON_UPDATE_REQUEST";
export const PERSON_UPDATE_SUCCESS = "PERSON_UPDATE_SUCCESS";
export const PERSON_UPDATE_ERROR = "PERSON_UPDATE_ERROR";
export const PERSON_UPDATE_RESET = "PERSON_UPDATE_RESET";

export const PERSON_DELETE = "PERSON_DELETE";
export const PERSON_DELETE_REQUEST = "PERSON_DELETE_REQUEST";
export const PERSON_DELETE_SUCCESS = "PERSON_DELETE_SUCCESS";
export const PERSON_DELETE_ERROR = "PERSON_DELETE_ERROR";
export const PERSON_DELETE_RESET = "PERSON_DELETE_RESET";

export const BUSINESS_LIST = "BUSINESS_LIST";
export const BUSINESS_LIST_REQUEST = "BUSINESS_LIST_REQUEST";
export const BUSINESS_LIST_SUCCESS = "BUSINESS_LIST_SUCCESS";
export const BUSINESS_LIST_ERROR = "BUSINESS_LIST_ERROR";

export const BUSINESS_DATA = "BUSINESS_DATA";
export const BUSINESS_DATA_REQUEST = "BUSINESS_DATA_REQUEST";
export const BUSINESS_DATA_SUCCESS = "BUSINESS_DATA_SUCCESS";
export const BUSINESS_DATA_ERROR = "BUSINESS_DATA_ERROR";

export const BUSINESS_CREATE = "BUSINESS_CREATE";
export const BUSINESS_CREATE_REQUEST = "BUSINESS_CREATE_REQUEST";
export const BUSINESS_CREATE_SUCCESS = "BUSINESS_CREATE_SUCCESS";
export const BUSINESS_CREATE_ERROR = "BUSINESS_CREATE_ERROR";
export const BUSINESS_CREATE_RESET = "BUSINESS_CREATE_RESET";

export const BUSINESS_UPDATE = "BUSINESS_UPDATE";
export const BUSINESS_UPDATE_REQUEST = "BUSINESS_UPDATE_REQUEST";
export const BUSINESS_UPDATE_SUCCESS = "BUSINESS_UPDATE_SUCCESS";
export const BUSINESS_UPDATE_ERROR = "BUSINESS_UPDATE_ERROR";
export const BUSINESS_UPDATE_RESET = "BUSINESS_UPDATE_RESET";

export const BUSINESS_DELETE = "BUSINESS_DELETE";
export const BUSINESS_DELETE_REQUEST = "BUSINESS_DELETE_REQUEST";
export const BUSINESS_DELETE_SUCCESS = "BUSINESS_DELETE_SUCCESS";
export const BUSINESS_DELETE_ERROR = "BUSINESS_DELETE_ERROR";
export const BUSINESS_DELETE_RESET = "BUSINESS_DELETE_RESET";
